apiVersion: v1
kind: Service
metadata:
  name: tussle-__ARTICULON_ENV__-api
  labels:
    app: tussle-__ARTICULON_ENV__-api
  name: tussle-__ARTICULON_ENV__-api
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5496
  selector:
    app: tussle-__ARTICULON_ENV__-api
  sessionAffinity: None
  type: ClusterIP

