steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: Build API Server Docker Image
    args:
      - "--destination=gcr.io/tussle/tussle-api:$REVISION_ID"
      - "--destination=gcr.io/tussle/tussle-api:latest"
      - "--cache=true"
      - "--cache-ttl=720h"
      - "--snapshot-mode=time"
      - "--build-arg"
      - "TUSSLE_ENV=$_TUSSLE_ENV"
      - "--build-arg"
      - "REVISION_ID=$REVISION_ID"
      - "-f"
      - "deployment/api/Dockerfile"
    timeout: 1200s
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'cluster-info'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=tussle-central'
    timeout: 30s
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update Deployment on Kubernetes
    entrypoint: /bin/bash
    args:
      - "./deployment/api/update_api_server.sh"
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=tussle-central'
      - 'TUSSLE_ENV=$_TUSSLE_ENV'
      - 'REVISION_ID=$REVISION_ID'
    timeout: 600s
timeout: 15000s
options:
  machineType: 'E2_MEDIUM'
