apiVersion: v1
kind: Service
metadata:
  labels:
    app: tussle-__ARTICULON_ENV__-frontend
  name: tussle-__ARTICULON_ENV__-frontend
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: tussle-__ARTICULON_ENV__-frontend
  sessionAffinity: None
  type: LoadBalancer
